#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_DinoHeadButtTrex

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "UnionRun_classes.hpp"
#include "ABP_DinoHeadButtTrex_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_DinoHeadButtTrex.ABP_DinoHeadButtTrex_C
// 0x04A0 (0x0810 - 0x0370)
class UABP_DinoHeadButtTrex_C final : public UHeadButtTrexAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct ABP_DinoHeadButtTrex::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;         // 0x0378(0x0002)(HasGetValueTypeHash)
	uint8                                         Pad_37A[0x6];                                      // 0x037A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0380(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0388(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0390(0x0020)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x03B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x03D8(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0400(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x0448(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0468(0x0048)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x04B0(0x0020)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x04D0(0x0020)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x04F0(0x00C8)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x05B8(0x0080)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x0638(0x0028)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0660(0x0048)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x06A8(0x00F0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x0798(0x0028)()
	struct FAnimNode_Mirror                       AnimGraphNode_Mirror;                              // 0x07C0(0x0048)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AnimNotify_AppearEnd();
	void AnimNotify_DestroyRock();
	void AnimNotify_Tremor();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DinoHeadButtTrex_AnimGraphNode_TransitionResult_960A3C404B9950BC4D102E827B208E0A();
	void ExecuteUbergraph_ABP_DinoHeadButtTrex(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_DinoHeadButtTrex_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_DinoHeadButtTrex_C")
	}
	static class UABP_DinoHeadButtTrex_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_DinoHeadButtTrex_C>();
	}
};
DUMPER7_ASSERTS_UABP_DinoHeadButtTrex_C;

}

