#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_DinoHeadButtTrex

#include "Basic.hpp"

#include "ABP_DinoHeadButtTrex_classes.hpp"
#include "ABP_DinoHeadButtTrex_parameters.hpp"


namespace SDK
{

// Function ABP_DinoHeadButtTrex.ABP_DinoHeadButtTrex_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_DinoHeadButtTrex_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_DinoHeadButtTrex_C", "AnimGraph");

	Params::ABP_DinoHeadButtTrex_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_DinoHeadButtTrex.ABP_DinoHeadButtTrex_C.AnimNotify_AppearEnd
// (BlueprintCallable, BlueprintEvent)

void UABP_DinoHeadButtTrex_C::AnimNotify_AppearEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_DinoHeadButtTrex_C", "AnimNotify_AppearEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_DinoHeadButtTrex.ABP_DinoHeadButtTrex_C.AnimNotify_DestroyRock
// (BlueprintCallable, BlueprintEvent)

void UABP_DinoHeadButtTrex_C::AnimNotify_DestroyRock()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_DinoHeadButtTrex_C", "AnimNotify_DestroyRock");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_DinoHeadButtTrex.ABP_DinoHeadButtTrex_C.AnimNotify_Tremor
// (BlueprintCallable, BlueprintEvent)

void UABP_DinoHeadButtTrex_C::AnimNotify_Tremor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_DinoHeadButtTrex_C", "AnimNotify_Tremor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_DinoHeadButtTrex.ABP_DinoHeadButtTrex_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DinoHeadButtTrex_AnimGraphNode_TransitionResult_960A3C404B9950BC4D102E827B208E0A
// (BlueprintEvent)

void UABP_DinoHeadButtTrex_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DinoHeadButtTrex_AnimGraphNode_TransitionResult_960A3C404B9950BC4D102E827B208E0A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_DinoHeadButtTrex_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_DinoHeadButtTrex_AnimGraphNode_TransitionResult_960A3C404B9950BC4D102E827B208E0A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_DinoHeadButtTrex.ABP_DinoHeadButtTrex_C.ExecuteUbergraph_ABP_DinoHeadButtTrex
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_DinoHeadButtTrex_C::ExecuteUbergraph_ABP_DinoHeadButtTrex(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_DinoHeadButtTrex_C", "ExecuteUbergraph_ABP_DinoHeadButtTrex");

	Params::ABP_DinoHeadButtTrex_C_ExecuteUbergraph_ABP_DinoHeadButtTrex Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

