#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_HoldWeight

#include "Basic.hpp"

#include "ABPT_HoldItem_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_HoldWeight.ABP_HoldWeight_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0D30 - 0x0D30)
struct ABP_HoldWeight::FAnimBlueprintGeneratedConstantData final : public ABPT_HoldItem::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_ABP_HoldWeight__FAnimBlueprintGeneratedConstantData;

}

