#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_BingoBall

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_BingoBall.ABP_BingoBall_C
// 0x0090 (0x0400 - 0x0370)
class UABP_BingoBall_C final : public UAnimInstance
{
public:
	uint8                                         Pad_368[0x8];                                      // 0x0368(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0370(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0378(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0380(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0388(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x03A8(0x0048)()
	class AGimmickBingoBall*                      OwnerActor;                                        // 0x03F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void AnimNotify_Ball_11();
	void AnimNotify_Ball_15();
	void AnimNotify_Ball_20();
	void AnimNotify_Ball_27();
	void AnimNotify_Ball_33();
	void AnimNotify_Ball_39();
	void AnimNotify_Ball_42();
	void AnimNotify_Ball_8();
	void ExecuteUbergraph_ABP_BingoBall(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_BingoBall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_BingoBall_C")
	}
	static class UABP_BingoBall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_BingoBall_C>();
	}
};
DUMPER7_ASSERTS_UABP_BingoBall_C;

}

