#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BingoBall

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BingoBall.BP_BingoBall_C
// 0x0000 (0x05F0 - 0x05F0)
class ABP_BingoBall_C final : public AGimmickBingoBall
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BingoBall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BingoBall_C")
	}
	static class ABP_BingoBall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BingoBall_C>();
	}
};
DUMPER7_ASSERTS_ABP_BingoBall_C;

}

