#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CubemapCaptureGameMode

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CubemapCaptureGameMode.BP_CubemapCaptureGameMode_C
// 0x0008 (0x0330 - 0x0328)
class ABP_CubemapCaptureGameMode_C final : public AGameModeBase
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0328(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CubemapCaptureGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CubemapCaptureGameMode_C")
	}
	static class ABP_CubemapCaptureGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CubemapCaptureGameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_CubemapCaptureGameMode_C;

}

