#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CactusVATBreakObject

#include "Basic.hpp"

#include "BP_CactusVATBreakObject_classes.hpp"
#include "BP_CactusVATBreakObject_parameters.hpp"


namespace SDK
{

// Function BP_CactusVATBreakObject.BP_CactusVATBreakObject_C.ExecuteUbergraph_BP_CactusVATBreakObject
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CactusVATBreakObject_C::ExecuteUbergraph_BP_CactusVATBreakObject(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CactusVATBreakObject_C", "ExecuteUbergraph_BP_CactusVATBreakObject");

	Params::BP_CactusVATBreakObject_C_ExecuteUbergraph_BP_CactusVATBreakObject Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CactusVATBreakObject.BP_CactusVATBreakObject_C.OnPlayBreakEvent
// (Event, Public, BlueprintEvent)

void ABP_CactusVATBreakObject_C::OnPlayBreakEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CactusVATBreakObject_C", "OnPlayBreakEvent");

	UObject::ProcessEvent(Func, nullptr);
}

}

