#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraCollision

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraCollision.BP_CameraCollision_C
// 0x0000 (0x05E0 - 0x05E0)
class ABP_CameraCollision_C final : public ACameraCollision
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CameraCollision_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CameraCollision_C")
	}
	static class ABP_CameraCollision_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CameraCollision_C>();
	}
};
DUMPER7_ASSERTS_ABP_CameraCollision_C;

}

