#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedRingFactory

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"
#include "Engine_structs.hpp"
#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DroppedRingFactory.BP_DroppedRingFactory_C
// 0x0010 (0x0E50 - 0x0E40)
class ABP_DroppedRingFactory_C final : public ADroppedRingFactory
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0E40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0E48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void OnPlayDroppedRingSound_Small(ESoundPan SoundPan);
	void OnPlayDroppedRingSound_Medium(ESoundPan SoundPan);
	void OnPlayDroppedRingSound_Large(ESoundPan SoundPan);
	void OnPlayDroppedRingSound_HIT_01(const struct FVector& Position);
	void OnPlayDroppedRingSound_DAMAGE_01(ESoundPan SoundPan);
	void ExecuteUbergraph_BP_DroppedRingFactory(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroppedRingFactory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroppedRingFactory_C")
	}
	static class ABP_DroppedRingFactory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroppedRingFactory_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroppedRingFactory_C;

}

