#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DinoTrex

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DinoTrex.BP_DinoTrex_C
// 0x0010 (0x0740 - 0x0730)
class ABP_DinoTrex_C final : public AEnemyTrex
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0730(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_DinoTrex(int32 EntryPoint);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DinoTrex_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DinoTrex_C")
	}
	static class ABP_DinoTrex_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DinoTrex_C>();
	}
};
DUMPER7_ASSERTS_ABP_DinoTrex_C;

}

