#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DinoPtero

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_DinoPtero.BP_DinoPtero_C.ExecuteUbergraph_BP_DinoPtero
// 0x0004 (0x0004 - 0x0000)
struct BP_DinoPtero_C_ExecuteUbergraph_BP_DinoPtero final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_DinoPtero_C_ExecuteUbergraph_BP_DinoPtero;

}

