#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedRingFactory

#include "Basic.hpp"

#include "BP_DroppedRingFactory_classes.hpp"
#include "BP_DroppedRingFactory_parameters.hpp"


namespace SDK
{

// Function BP_DroppedRingFactory.BP_DroppedRingFactory_C.OnPlayDroppedRingSound_Small
// (Event, Public, BlueprintEvent)
// Parameters:
// ESoundPan                               SoundPan                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedRingFactory_C::OnPlayDroppedRingSound_Small(ESoundPan SoundPan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedRingFactory_C", "OnPlayDroppedRingSound_Small");

	Params::BP_DroppedRingFactory_C_OnPlayDroppedRingSound_Small Parms{};

	Parms.SoundPan = SoundPan;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedRingFactory.BP_DroppedRingFactory_C.OnPlayDroppedRingSound_Medium
// (Event, Public, BlueprintEvent)
// Parameters:
// ESoundPan                               SoundPan                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedRingFactory_C::OnPlayDroppedRingSound_Medium(ESoundPan SoundPan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedRingFactory_C", "OnPlayDroppedRingSound_Medium");

	Params::BP_DroppedRingFactory_C_OnPlayDroppedRingSound_Medium Parms{};

	Parms.SoundPan = SoundPan;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedRingFactory.BP_DroppedRingFactory_C.OnPlayDroppedRingSound_Large
// (Event, Public, BlueprintEvent)
// Parameters:
// ESoundPan                               SoundPan                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedRingFactory_C::OnPlayDroppedRingSound_Large(ESoundPan SoundPan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedRingFactory_C", "OnPlayDroppedRingSound_Large");

	Params::BP_DroppedRingFactory_C_OnPlayDroppedRingSound_Large Parms{};

	Parms.SoundPan = SoundPan;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedRingFactory.BP_DroppedRingFactory_C.OnPlayDroppedRingSound_HIT_01
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FVector&                   Position                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedRingFactory_C::OnPlayDroppedRingSound_HIT_01(const struct FVector& Position)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedRingFactory_C", "OnPlayDroppedRingSound_HIT_01");

	Params::BP_DroppedRingFactory_C_OnPlayDroppedRingSound_HIT_01 Parms{};

	Parms.Position = std::move(Position);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedRingFactory.BP_DroppedRingFactory_C.OnPlayDroppedRingSound_DAMAGE_01
// (Event, Public, BlueprintEvent)
// Parameters:
// ESoundPan                               SoundPan                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedRingFactory_C::OnPlayDroppedRingSound_DAMAGE_01(ESoundPan SoundPan)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedRingFactory_C", "OnPlayDroppedRingSound_DAMAGE_01");

	Params::BP_DroppedRingFactory_C_OnPlayDroppedRingSound_DAMAGE_01 Parms{};

	Parms.SoundPan = SoundPan;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroppedRingFactory.BP_DroppedRingFactory_C.ExecuteUbergraph_BP_DroppedRingFactory
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroppedRingFactory_C::ExecuteUbergraph_BP_DroppedRingFactory(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroppedRingFactory_C", "ExecuteUbergraph_BP_DroppedRingFactory");

	Params::BP_DroppedRingFactory_C_ExecuteUbergraph_BP_DroppedRingFactory Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

