#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroppedItemBoxFactory

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DroppedItemBoxFactory.BP_DroppedItemBoxFactory_C
// 0x0000 (0x0350 - 0x0350)
class ABP_DroppedItemBoxFactory_C final : public ADroppedItemBoxFactory
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroppedItemBoxFactory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroppedItemBoxFactory_C")
	}
	static class ABP_DroppedItemBoxFactory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroppedItemBoxFactory_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroppedItemBoxFactory_C;

}

