#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FX_TravelRing_DesidePanel

#include "Basic.hpp"

#include "BP_FX_TravelRing_DesidePanel_classes.hpp"
#include "BP_FX_TravelRing_DesidePanel_parameters.hpp"


namespace SDK
{

// Function BP_FX_TravelRing_DesidePanel.BP_FX_TravelRing_DesidePanel_C.ExecuteUbergraph_BP_FX_TravelRing_DesidePanel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FX_TravelRing_DesidePanel_C::ExecuteUbergraph_BP_FX_TravelRing_DesidePanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FX_TravelRing_DesidePanel_C", "ExecuteUbergraph_BP_FX_TravelRing_DesidePanel");

	Params::BP_FX_TravelRing_DesidePanel_C_ExecuteUbergraph_BP_FX_TravelRing_DesidePanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FX_TravelRing_DesidePanel.BP_FX_TravelRing_DesidePanel_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_FX_TravelRing_DesidePanel_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FX_TravelRing_DesidePanel_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FX_TravelRing_DesidePanel.BP_FX_TravelRing_DesidePanel_C.SetNoHidden
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_FX_TravelRing_DesidePanel_C::SetNoHidden()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FX_TravelRing_DesidePanel_C", "SetNoHidden");

	UObject::ProcessEvent(Func, nullptr);
}

}

