#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FX_TravelRing_Wave

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_FX_TravelRing_Wave.BP_FX_TravelRing_Wave_C.ExecuteUbergraph_BP_FX_TravelRing_Wave
// 0x0040 (0x0040 - 0x0000)
struct BP_FX_TravelRing_Wave_C_ExecuteUbergraph_BP_FX_TravelRing_Wave final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAppRaceEventManager*                   CallFunc_GetWorldSubsystem_ReturnValue;            // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class ABP_FX_TravelRing_Wave_C> CallFunc_Conv_ObjectToSoftObjectReference_ReturnValue; // 0x0010(0x0028)(UObjectWrapper, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_FX_TravelRing_Wave_C_ExecuteUbergraph_BP_FX_TravelRing_Wave;

}

