#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FracturedRock

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FracturedRock.BP_FracturedRock_C
// 0x0038 (0x03B0 - 0x0378)
class ABP_FracturedRock_C final : public AGimmickFracturedRock
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UMaterialInstanceDynamic*               m_marerialInstanceDynamic_0;                       // 0x0380(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               m_marerialInstanceDynamic_1;                       // 0x0388(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        DisplayFrame;                                      // 0x0390(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        globalPieceScaleMultiplier;                        // 0x0398(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInstanceDynamic*>       MaterialInstanceArray;                             // 0x03A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_BP_FracturedRock(int32 EntryPoint);
	void OnPlayAnimation(float displayFram, float globalPieceScaleMultiplier_0);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FracturedRock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FracturedRock_C")
	}
	static class ABP_FracturedRock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FracturedRock_C>();
	}
};
DUMPER7_ASSERTS_ABP_FracturedRock_C;

}

