#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GuidedJumpStand

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_GuidedJumpStand.BP_GuidedJumpStand_C.ExecuteUbergraph_BP_GuidedJumpStand
// 0x0004 (0x0004 - 0x0000)
struct BP_GuidedJumpStand_C_ExecuteUbergraph_BP_GuidedJumpStand final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_GuidedJumpStand_C_ExecuteUbergraph_BP_GuidedJumpStand;

}

