#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemBox

#include "Basic.hpp"

#include "BP_ItemBox_classes.hpp"
#include "BP_ItemBox_parameters.hpp"


namespace SDK
{

// Function BP_ItemBox.BP_ItemBox_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ItemBox_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemBox_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ItemBox.BP_ItemBox_C.OnPlayTakeSound
// (Event, Public, BlueprintEvent)

void ABP_ItemBox_C::OnPlayTakeSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemBox_C", "OnPlayTakeSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ItemBox.BP_ItemBox_C.OnPlayForceFeedback
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   LocalPlayerIndex                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ItemBox_C::OnPlayForceFeedback(int32 LocalPlayerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemBox_C", "OnPlayForceFeedback");

	Params::BP_ItemBox_C_OnPlayForceFeedback Parms{};

	Parms.LocalPlayerIndex = LocalPlayerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemBox.BP_ItemBox_C.OnHitRacer
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   RacerIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ItemBox_C::OnHitRacer(int32 RacerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemBox_C", "OnHitRacer");

	Params::BP_ItemBox_C_OnHitRacer Parms{};

	Parms.RacerIndex = RacerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ItemBox.BP_ItemBox_C.ExecuteUbergraph_BP_ItemBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ItemBox_C::ExecuteUbergraph_BP_ItemBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ItemBox_C", "ExecuteUbergraph_BP_ItemBox");

	Params::BP_ItemBox_C_ExecuteUbergraph_BP_ItemBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

