#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PackageRingEffect

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"


namespace SDK::Params
{

// Function BP_PackageRingEffect.BP_PackageRingEffect_C.ExecuteUbergraph_BP_PackageRingEffect
// 0x0010 (0x0010 - 0x0000)
struct BP_PackageRingEffect_C_ExecuteUbergraph_BP_PackageRingEffect final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSoundHandle                           CallFunc_SoundBuildPlayer_ReturnValue;             // 0x0004(0x0004)()
	struct FSoundHandle                           CallFunc_SetPanSplit_ReturnValue;                  // 0x0008(0x0004)()
	struct FSoundHandle                           CallFunc_Play_ReturnValue;                         // 0x000C(0x0004)()
};
DUMPER7_ASSERTS_BP_PackageRingEffect_C_ExecuteUbergraph_BP_PackageRingEffect;

}

