#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PackageRingEffect

#include "Basic.hpp"

#include "BP_PackageRingEffect_classes.hpp"
#include "BP_PackageRingEffect_parameters.hpp"


namespace SDK
{

// Function BP_PackageRingEffect.BP_PackageRingEffect_C.OnPlayTakeRingSound
// (Event, Public, BlueprintEvent)

void ABP_PackageRingEffect_C::OnPlayTakeRingSound()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PackageRingEffect_C", "OnPlayTakeRingSound");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PackageRingEffect.BP_PackageRingEffect_C.ExecuteUbergraph_BP_PackageRingEffect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PackageRingEffect_C::ExecuteUbergraph_BP_PackageRingEffect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PackageRingEffect_C", "ExecuteUbergraph_BP_PackageRingEffect");

	Params::BP_PackageRingEffect_C_ExecuteUbergraph_BP_PackageRingEffect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

