#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Respot

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Respot.BP_Respot_C.ExecuteUbergraph_BP_Respot
// 0x0004 (0x0004 - 0x0000)
struct BP_Respot_C_ExecuteUbergraph_BP_Respot final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Respot_C_ExecuteUbergraph_BP_Respot;

}

