#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Respot

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Respot.BP_Respot_C
// 0x0010 (0x06D0 - 0x06C0)
class ABP_Respot_C final : public ARespotObject
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_Respot(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Respot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Respot_C")
	}
	static class ABP_Respot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Respot_C>();
	}
};
DUMPER7_ASSERTS_ABP_Respot_C;

}

