#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaceEndMenuSequence

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"
#include "Engine_structs.hpp"
#include "UNION_structs.hpp"
#include "UNION_classes.hpp"
#include "UnionRun_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C
// 0x0068 (0x0580 - 0x0518)
class ABP_RaceEndMenuSequence_C final : public ARaceEndMenuSequence
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0518(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ARacePlayerController*                  RacePlayerController;                              // 0x0520(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UWBP_EndMenu_C*                         EndMenuWidget;                                     // 0x0528(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	ERaceEndMenuItem                              LastSelectedItem;                                  // 0x0530(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_531[0x7];                                      // 0x0531(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUnionUISceneBase*                      PopupWidget;                                       // 0x0538(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UHintPopupWindow*                       TipsWindow;                                        // 0x0540(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	ECommonRaceMenuContentId                      SelectedContentId;                                 // 0x0548(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_549[0x7];                                      // 0x0549(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USquadContext*                          SquadLobby;                                        // 0x0550(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsError;                                          // 0x0558(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESquadLobbyMatchContinuation                  Match_Continuation;                                // 0x0559(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_55A[0x6];                                      // 0x055A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_ReadySequenceActor_C*               ReadySequenceActor;                                // 0x0560(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UUnionUIPopupWindowBase*                ConfirmPopupWidget;                                // 0x0568(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_Friend_Popup_Window_C*             CheckLobbyInvitePopup;                             // 0x0570(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_Friend_Popup_WindowAnimation_C*    CheckLobbyInvitePopupAnimation;                    // 0x0578(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void WarnPop();
	void ReshowEndMenu();
	void ReadyEndEvent();
	void ReadyConfirmInitialize();
	void ReadyCancelEvent();
	void PopupWindow_Cancel();
	void OnUpdateStateSelect(float InDeltaTime);
	void OnUISceneCancelEvent_Event(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void OnTipsWindowCloseEnd_Event();
	void OnSaveEnd(ESaveDataStatus Status);
	void OnPreDecision();
	void OnInitStateSelect();
	void OnInitStateIdle();
	void OnInitStateExit();
	void OnInitStateCheckLobbyInvite();
	void OnInitialize();
	void OnFinalize();
	void OnExitStateSelect();
	void OnExitStateGotoTopMennu();
	void OnExitStateGotoSquadLobby();
	void OnExitStateGotoMatchingLobby();
	void OnDecide_PopupWindow(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void OnDecide(ECommonRaceMenuContentId SelectedContentId_0);
	void OnCloseGadgetPlateReady();
	void OnCheckFriendListButtonDecision(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex);
	void HideEndMenu();
	void GetTipsHintId(EHintId* OutTipsHintId);
	void ExecuteUbergraph_BP_RaceEndMenuSequence(int32 EntryPoint);
	void Debug_Force_Decide();
	void CreateTipsWindow(EHintId InHintId);
	void CreateGadgetPlateReadyActor(bool Optimize);
	void CreateConfirmationPopup(EPopupWindowType WindowType, EPopupWindowButtonType ButtonType, bool Attention, class UUnionUISceneBase** WindowWidget);
	void CheckNextStateIsGadget(bool ExitTopMenu, bool* NextIsGadget);
	void CheckLobbyAnimationOutFinish();
	void CheckEndMenuContentSet(ECommonRaceMenuContentId InContentId, struct FCommonRaceMenuContentRow* OutContent, bool* bOutIsValid);
	void AfterDecided();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RaceEndMenuSequence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RaceEndMenuSequence_C")
	}
	static class ABP_RaceEndMenuSequence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RaceEndMenuSequence_C>();
	}
};
DUMPER7_ASSERTS_ABP_RaceEndMenuSequence_C;

}

