#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RaceEndMenuSequence

#include "Basic.hpp"

#include "BP_RaceEndMenuSequence_classes.hpp"
#include "BP_RaceEndMenuSequence_parameters.hpp"


namespace SDK
{

// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.WarnPop
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::WarnPop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "WarnPop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.ReshowEndMenu
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::ReshowEndMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "ReshowEndMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.ReadyEndEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::ReadyEndEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "ReadyEndEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.ReadyConfirmInitialize
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::ReadyConfirmInitialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "ReadyConfirmInitialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.ReadyCancelEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::ReadyCancelEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "ReadyCancelEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.PopupWindow_Cancel
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::PopupWindow_Cancel()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "PopupWindow_Cancel");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnUpdateStateSelect
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::OnUpdateStateSelect(float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnUpdateStateSelect");

	Params::BP_RaceEndMenuSequence_C_OnUpdateStateSelect Parms{};

	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnUISceneCancelEvent_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::OnUISceneCancelEvent_Event(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnUISceneCancelEvent_Event");

	Params::BP_RaceEndMenuSequence_C_OnUISceneCancelEvent_Event Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnTipsWindowCloseEnd_Event
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnTipsWindowCloseEnd_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnTipsWindowCloseEnd_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnSaveEnd
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ESaveDataStatus                         Status                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::OnSaveEnd(ESaveDataStatus Status)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnSaveEnd");

	Params::BP_RaceEndMenuSequence_C_OnSaveEnd Parms{};

	Parms.Status = Status;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnPreDecision
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnPreDecision()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnPreDecision");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnInitStateSelect
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnInitStateSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnInitStateSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnInitStateIdle
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnInitStateIdle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnInitStateIdle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnInitStateExit
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnInitStateExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnInitStateExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnInitStateCheckLobbyInvite
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnInitStateCheckLobbyInvite()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnInitStateCheckLobbyInvite");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnInitialize
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnInitialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnInitialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnFinalize
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnFinalize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnFinalize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnExitStateSelect
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnExitStateSelect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnExitStateSelect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnExitStateGotoTopMennu
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnExitStateGotoTopMennu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnExitStateGotoTopMennu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnExitStateGotoSquadLobby
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnExitStateGotoSquadLobby()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnExitStateGotoSquadLobby");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnExitStateGotoMatchingLobby
// (Event, Protected, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnExitStateGotoMatchingLobby()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnExitStateGotoMatchingLobby");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnDecide_PopupWindow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::OnDecide_PopupWindow(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnDecide_PopupWindow");

	Params::BP_RaceEndMenuSequence_C_OnDecide_PopupWindow Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnDecide
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ECommonRaceMenuContentId                SelectedContentId_0                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::OnDecide(ECommonRaceMenuContentId SelectedContentId_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnDecide");

	Params::BP_RaceEndMenuSequence_C_OnDecide Parms{};

	Parms.SelectedContentId_0 = SelectedContentId_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnCloseGadgetPlateReady
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::OnCloseGadgetPlateReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnCloseGadgetPlateReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.OnCheckFriendListButtonDecision
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUnionUIButtonBase*               Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   PanelIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ButtonIndex                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::OnCheckFriendListButtonDecision(class UUnionUIButtonBase* Button, int32 PanelIndex, int32 ButtonIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "OnCheckFriendListButtonDecision");

	Params::BP_RaceEndMenuSequence_C_OnCheckFriendListButtonDecision Parms{};

	Parms.Button = Button;
	Parms.PanelIndex = PanelIndex;
	Parms.ButtonIndex = ButtonIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.HideEndMenu
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::HideEndMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "HideEndMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.GetTipsHintId
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EHintId*                                OutTipsHintId                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::GetTipsHintId(EHintId* OutTipsHintId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "GetTipsHintId");

	Params::BP_RaceEndMenuSequence_C_GetTipsHintId Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutTipsHintId != nullptr)
		*OutTipsHintId = Parms.OutTipsHintId;
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.ExecuteUbergraph_BP_RaceEndMenuSequence
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::ExecuteUbergraph_BP_RaceEndMenuSequence(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "ExecuteUbergraph_BP_RaceEndMenuSequence");

	Params::BP_RaceEndMenuSequence_C_ExecuteUbergraph_BP_RaceEndMenuSequence Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.Debug Force Decide
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::Debug_Force_Decide()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "Debug Force Decide");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.CreateTipsWindow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EHintId                                 InHintId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::CreateTipsWindow(EHintId InHintId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "CreateTipsWindow");

	Params::BP_RaceEndMenuSequence_C_CreateTipsWindow Parms{};

	Parms.InHintId = InHintId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.CreateGadgetPlateReadyActor
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Optimize                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::CreateGadgetPlateReadyActor(bool Optimize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "CreateGadgetPlateReadyActor");

	Params::BP_RaceEndMenuSequence_C_CreateGadgetPlateReadyActor Parms{};

	Parms.Optimize = Optimize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.CreateConfirmationPopup
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPopupWindowType                        WindowType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPopupWindowButtonType                  ButtonType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Attention                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UUnionUISceneBase**               WindowWidget                                           (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::CreateConfirmationPopup(EPopupWindowType WindowType, EPopupWindowButtonType ButtonType, bool Attention, class UUnionUISceneBase** WindowWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "CreateConfirmationPopup");

	Params::BP_RaceEndMenuSequence_C_CreateConfirmationPopup Parms{};

	Parms.WindowType = WindowType;
	Parms.ButtonType = ButtonType;
	Parms.Attention = Attention;

	UObject::ProcessEvent(Func, &Parms);

	if (WindowWidget != nullptr)
		*WindowWidget = Parms.WindowWidget;
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.CheckNextStateIsGadget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ExitTopMenu                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   NextIsGadget                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::CheckNextStateIsGadget(bool ExitTopMenu, bool* NextIsGadget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "CheckNextStateIsGadget");

	Params::BP_RaceEndMenuSequence_C_CheckNextStateIsGadget Parms{};

	Parms.ExitTopMenu = ExitTopMenu;

	UObject::ProcessEvent(Func, &Parms);

	if (NextIsGadget != nullptr)
		*NextIsGadget = Parms.NextIsGadget;
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.CheckLobbyAnimationOutFinish
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::CheckLobbyAnimationOutFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "CheckLobbyAnimationOutFinish");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.CheckEndMenuContentSet
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ECommonRaceMenuContentId                InContentId                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FCommonRaceMenuContentRow*       OutContent                                             (Parm, OutParm)
// bool*                                   bOutIsValid                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RaceEndMenuSequence_C::CheckEndMenuContentSet(ECommonRaceMenuContentId InContentId, struct FCommonRaceMenuContentRow* OutContent, bool* bOutIsValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "CheckEndMenuContentSet");

	Params::BP_RaceEndMenuSequence_C_CheckEndMenuContentSet Parms{};

	Parms.InContentId = InContentId;

	UObject::ProcessEvent(Func, &Parms);

	if (OutContent != nullptr)
		*OutContent = std::move(Parms.OutContent);

	if (bOutIsValid != nullptr)
		*bOutIsValid = Parms.bOutIsValid;
}


// Function BP_RaceEndMenuSequence.BP_RaceEndMenuSequence_C.AfterDecided
// (BlueprintCallable, BlueprintEvent)

void ABP_RaceEndMenuSequence_C::AfterDecided()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RaceEndMenuSequence_C", "AfterDecided");

	UObject::ProcessEvent(Func, nullptr);
}

}

