#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RingInstance

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RingInstance.BP_RingInstance_C
// 0x0000 (0x04E0 - 0x04E0)
class ABP_RingInstance_C final : public ARingInstanceObject
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RingInstance_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RingInstance_C")
	}
	static class ABP_RingInstance_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RingInstance_C>();
	}
};
DUMPER7_ASSERTS_ABP_RingInstance_C;

}

