#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SimpleAnim

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SimpleAnim.BP_SimpleAnim_C
// 0x0000 (0x02E8 - 0x02E8)
class ABP_SimpleAnim_C final : public ARaceObjectSimpleAnimation
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SimpleAnim_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SimpleAnim_C")
	}
	static class ABP_SimpleAnim_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SimpleAnim_C>();
	}
};
DUMPER7_ASSERTS_ABP_SimpleAnim_C;

}

