#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SequenceParameterActor

#include "Basic.hpp"

#include "UnionSystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SequenceParameterActor.BP_SequenceParameterActor_C
// 0x0010 (0x03C0 - 0x03B0)
class ABP_SequenceParameterActor_C final : public ASequenceParameterActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SequenceParameterActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SequenceParameterActor_C")
	}
	static class ABP_SequenceParameterActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SequenceParameterActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_SequenceParameterActor_C;

}

