#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TravelRingMainExitSpawner

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_TravelRingSpawnerBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TravelRingMainExitSpawner.BP_TravelRingMainExitSpawner_C
// 0x0008 (0x0380 - 0x0378)
class ABP_TravelRingMainExitSpawner_C final : public ABP_TravelRingSpawnerBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_TravelRingMainExitSpawner_C;     // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_TravelRingMainExitSpawner(int32 EntryPoint);
	void PostSpawnSequenceActor();
	void SetTravelRingState(uint8 TravelRingState_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TravelRingMainExitSpawner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TravelRingMainExitSpawner_C")
	}
	static class ABP_TravelRingMainExitSpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TravelRingMainExitSpawner_C>();
	}
};
DUMPER7_ASSERTS_ABP_TravelRingMainExitSpawner_C;

}

