#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TravelDecidePanelSpawner

#include "Basic.hpp"

#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TravelDecidePanelSpawner.BP_TravelDecidePanelSpawner_C
// 0x0000 (0x0368 - 0x0368)
class ABP_TravelDecidePanelSpawner_C final : public ACourseSequenceActorSpawner
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TravelDecidePanelSpawner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TravelDecidePanelSpawner_C")
	}
	static class ABP_TravelDecidePanelSpawner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TravelDecidePanelSpawner_C>();
	}
};
DUMPER7_ASSERTS_ABP_TravelDecidePanelSpawner_C;

}

