#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TravelRingMainExitSpawner

#include "Basic.hpp"

#include "BP_TravelRingMainExitSpawner_classes.hpp"
#include "BP_TravelRingMainExitSpawner_parameters.hpp"


namespace SDK
{

// Function BP_TravelRingMainExitSpawner.BP_TravelRingMainExitSpawner_C.ExecuteUbergraph_BP_TravelRingMainExitSpawner
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TravelRingMainExitSpawner_C::ExecuteUbergraph_BP_TravelRingMainExitSpawner(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TravelRingMainExitSpawner_C", "ExecuteUbergraph_BP_TravelRingMainExitSpawner");

	Params::BP_TravelRingMainExitSpawner_C_ExecuteUbergraph_BP_TravelRingMainExitSpawner Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TravelRingMainExitSpawner.BP_TravelRingMainExitSpawner_C.PostSpawnSequenceActor
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void ABP_TravelRingMainExitSpawner_C::PostSpawnSequenceActor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TravelRingMainExitSpawner_C", "PostSpawnSequenceActor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TravelRingMainExitSpawner.BP_TravelRingMainExitSpawner_C.SetTravelRingState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   TravelRingState_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_TravelRingMainExitSpawner_C::SetTravelRingState(uint8 TravelRingState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TravelRingMainExitSpawner_C", "SetTravelRingState");

	Params::BP_TravelRingMainExitSpawner_C_SetTravelRingState Parms{};

	Parms.TravelRingState_0 = TravelRingState_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

