#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TravelRingSpawnerBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UnionRun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_TravelRingSpawnerBase.BP_TravelRingSpawnerBase_C
// 0x0010 (0x0378 - 0x0368)
class ABP_TravelRingSpawnerBase_C : public ACourseSequenceActorSpawner
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	uint8                                         TravelRingState;                                   // 0x0370(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_TravelRingSpawnerBase(int32 EntryPoint);
	void PostSpawnSequenceActor();
	void ReceiveBeginPlay();
	void ResetSpawnTransform();
	void SetTravelRingState(uint8 TravelRingState_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_TravelRingSpawnerBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_TravelRingSpawnerBase_C")
	}
	static class ABP_TravelRingSpawnerBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_TravelRingSpawnerBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_TravelRingSpawnerBase_C;

}

