#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VATBreakObjectBase

#include "Basic.hpp"

#include "BP_VATBreakObjectBase_classes.hpp"
#include "BP_VATBreakObjectBase_parameters.hpp"


namespace SDK
{

// Function BP_VATBreakObjectBase.BP_VATBreakObjectBase_C.Play3DSound
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USoundAtomCue*                    PlaySoundCue                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_VATBreakObjectBase_C::Play3DSound(class USoundAtomCue* PlaySoundCue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_VATBreakObjectBase_C", "Play3DSound");

	Params::BP_VATBreakObjectBase_C_Play3DSound Parms{};

	Parms.PlaySoundCue = PlaySoundCue;

	UObject::ProcessEvent(Func, &Parms);
}

}

