#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_JudgeEndingState

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UNION_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPC_JudgeEndingState.BPC_JudgeEndingState_C
// 0x0008 (0x0118 - 0x0110)
class UBPC_JudgeEndingState_C final : public UJudgeEndingState
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0110(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BPC_JudgeEndingState(int32 EntryPoint);
	void OnInitState();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_JudgeEndingState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_JudgeEndingState_C")
	}
	static class UBPC_JudgeEndingState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_JudgeEndingState_C>();
	}
};
DUMPER7_ASSERTS_UBPC_JudgeEndingState_C;

}

