#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_FX_TravelRing_90_Close_ExitRing

#include "Basic.hpp"


namespace SDK::Params
{

// Function LS_FX_TravelRing_90_Close_ExitRing.LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C.ExecuteUbergraph_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP
// 0x0030 (0x0030 - 0x0000)
struct LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_ExecuteUbergraph_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_FX_TravelRing_C*                    K2Node_CustomEvent_BP_FX_TravelRing_Right;         // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FX_TravelRing_DesidePanel_C*        K2Node_CustomEvent_BP_FX_DesidePanel;              // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FX_Locator_C*                       K2Node_CustomEvent_01_Entrance_Locator;            // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FX_TravelRing_C*                    K2Node_CustomEvent_BP_FX_TravelRing_Left;          // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_FX_TravelRing_Floor_C*              K2Node_CustomEvent_BP_FX_TravelRing_Floor;         // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_ExecuteUbergraph_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP;

// Function LS_FX_TravelRing_90_Close_ExitRing.LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C.BP_FX_TravelRing_Right_Event_1
// 0x0008 (0x0008 - 0x0000)
struct LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_TravelRing_Right_Event_1 final
{
public:
	class ABP_FX_TravelRing_C*                    BP_FX_TravelRing_Right;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_TravelRing_Right_Event_1;

// Function LS_FX_TravelRing_90_Close_ExitRing.LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C.BP_FX_TravelRing_Left_Event_0
// 0x0008 (0x0008 - 0x0000)
struct LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_TravelRing_Left_Event_0 final
{
public:
	class ABP_FX_TravelRing_C*                    BP_FX_TravelRing_Left;                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_TravelRing_Left_Event_0;

// Function LS_FX_TravelRing_90_Close_ExitRing.LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C.BP_FX_TravelRing_Floor_Event_0
// 0x0008 (0x0008 - 0x0000)
struct LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_TravelRing_Floor_Event_0 final
{
public:
	class ABP_FX_TravelRing_Floor_C*              BP_FX_TravelRing_Floor;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_TravelRing_Floor_Event_0;

// Function LS_FX_TravelRing_90_Close_ExitRing.LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C.BP_FX_DesidePanel_Event_SetNoHidden
// 0x0008 (0x0008 - 0x0000)
struct LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_DesidePanel_Event_SetNoHidden final
{
public:
	class ABP_FX_TravelRing_DesidePanel_C*        BP_FX_DesidePanel;                                 // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_BP_FX_DesidePanel_Event_SetNoHidden;

// Function LS_FX_TravelRing_90_Close_ExitRing.LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C.01_Entrance_Locator_Event_SetMPCTravelRing
// 0x0008 (0x0008 - 0x0000)
struct LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_Zero1_Entrance_Locator_Event_SetMPCTravelRing final
{
public:
	class ABP_FX_Locator_C*                       Zero1_Entrance_Locator;                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_LS_FX_TravelRing_90_Close_ExitRing_DirectorBP_C_Zero1_Entrance_Locator_Event_SetMPCTravelRing;

}

