#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_Rival_Car_Sonic_con

#include "Basic.hpp"

#include "LS_Rival_Car_Sonic_con_classes.hpp"
#include "LS_Rival_Car_Sonic_con_parameters.hpp"


namespace SDK
{

// Function LS_Rival_Car_Sonic_con.LS_Rival_Car_Sonic_con_DirectorBP_C.OnSlideScreen
// (BlueprintCallable, BlueprintEvent)

void ULS_Rival_Car_Sonic_con_DirectorBP_C::OnSlideScreen()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Rival_Car_Sonic_con_DirectorBP_C", "OnSlideScreen");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_Rival_Car_Sonic_con.LS_Rival_Car_Sonic_con_DirectorBP_C.OnPauseScene
// (BlueprintCallable, BlueprintEvent)

void ULS_Rival_Car_Sonic_con_DirectorBP_C::OnPauseScene()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Rival_Car_Sonic_con_DirectorBP_C", "OnPauseScene");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_Rival_Car_Sonic_con.LS_Rival_Car_Sonic_con_DirectorBP_C.OnCreated
// (Event, Public, BlueprintEvent)

void ULS_Rival_Car_Sonic_con_DirectorBP_C::OnCreated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Rival_Car_Sonic_con_DirectorBP_C", "OnCreated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LS_Rival_Car_Sonic_con.LS_Rival_Car_Sonic_con_DirectorBP_C.ExecuteUbergraph_LS_Rival_Car_Sonic_con_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULS_Rival_Car_Sonic_con_DirectorBP_C::ExecuteUbergraph_LS_Rival_Car_Sonic_con_DirectorBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LS_Rival_Car_Sonic_con_DirectorBP_C", "ExecuteUbergraph_LS_Rival_Car_Sonic_con_DirectorBP");

	Params::LS_Rival_Car_Sonic_con_DirectorBP_C_ExecuteUbergraph_LS_Rival_Car_Sonic_con_DirectorBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

