#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: mariaUploadPlugin

#include "Basic.hpp"


namespace SDK
{

// Enum mariaUploadPlugin.EMariaDevelopLogCategory
// NumValues: 0x0007
enum class EMariaDevelopLogCategory : uint8
{
	Verbose                                  = 0,
	Info                                     = 1,
	Display                                  = 2,
	Warning                                  = 3,
	Error                                    = 4,
	None                                     = 255,
	EMariaDevelopLogCategory_MAX             = 256,
};

// Enum mariaUploadPlugin.EMariaInitializeAuthResult
// NumValues: 0x0010
enum class EMariaInitializeAuthResult : uint8
{
	Pending                                  = 0,
	Success                                  = 1,
	Error                                    = 2,
	Cancelled                                = 3,
	NeedRetry                                = 4,
	NoUsers                                  = 5,
	FailAuth                                 = 6,
	AuthServer                               = 7,
	NSAUnavailable                           = 8,
	Unregistered                             = 9,
	Banned                                   = 10,
	ExternalError                            = 11,
	NSAccountLink                            = 12,
	NeedInteraction                          = 13,
	InapropriateCall                         = 255,
	EMariaInitializeAuthResult_MAX           = 256,
};

// Enum mariaUploadPlugin.EMariaDevMode
// NumValues: 0x0005
enum class EMariaDevMode : uint8
{
	Retail                                   = 0,
	Staging                                  = 1,
	Develop                                  = 2,
	Internal                                 = 3,
	EMariaDevMode_MAX                        = 4,
};

// Enum mariaUploadPlugin.EMariaEpicLoginType
// NumValues: 0x0005
enum class EMariaEpicLoginType : uint8
{
	Auto                                     = 0,
	AccountPortal                            = 1,
	ExchangeCode                             = 2,
	Developer                                = 3,
	EMariaEpicLoginType_MAX                  = 4,
};

// Enum mariaUploadPlugin.EMariaSegaAccountLinkTarget
// NumValues: 0x0003
enum class EMariaSegaAccountLinkTarget : uint8
{
	Platform                                 = 0,
	UserID                                   = 1,
	EMariaSegaAccountLinkTarget_MAX          = 2,
};

// Enum mariaUploadPlugin.EMariaSegaAccountType
// NumValues: 0x0004
enum class EMariaSegaAccountType : uint8
{
	Unknown                                  = 0,
	Child                                    = 1,
	General                                  = 2,
	EMariaSegaAccountType_MAX                = 3,
};

// Enum mariaUploadPlugin.EMariaXboxUserPickMode
// NumValues: 0x0004
enum class EMariaXboxUserPickMode : uint8
{
	Default                                  = 0,
	DefaultOrPick                            = 1,
	Pick                                     = 2,
	EMariaXboxUserPickMode_MAX               = 3,
};

// ScriptStruct mariaUploadPlugin.MariaQRCode
// 0x0018 (0x0018 - 0x0000)
struct alignas(0x08) FMariaQRCode final
{
public:
	uint8                                         Pad_0[0x18];                                       // 0x0000(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FMariaQRCode;

// ScriptStruct mariaUploadPlugin.MariaTableRow
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FMariaTableRow final
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FMariaTableRow;

}

