#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_FX_TravelRing_Main_LevelInstance_17

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UNION_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SL_FX_TravelRing_Main_LevelInstance_17.SL_FX_TravelRing_Main_C
// 0x0010 (0x08B8 - 0x08A8)
class ASL_FX_TravelRing_Main_C final : public AUnionTravelRingLevelActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ALevelSequenceActor*                    Zero1_TravelRing_ExecuteUbergraph_SL_FX_TravelRing_Main_RefProperty; // 0x08B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void SetSequence(uint8 SequenceNo);
	void SetDrawMode(int32 ModeNo);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_SL_FX_TravelRing_Main(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SL_FX_TravelRing_Main_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SL_FX_TravelRing_Main_C")
	}
	static class ASL_FX_TravelRing_Main_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASL_FX_TravelRing_Main_C>();
	}
};
DUMPER7_ASSERTS_ASL_FX_TravelRing_Main_C;

}

