#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_FX_TravelRing_Another_LevelInstance_18

#include "Basic.hpp"


namespace SDK::Params
{

// Function SL_FX_TravelRing_Another_LevelInstance_18.SL_FX_TravelRing_Another_C.ExecuteUbergraph_SL_FX_TravelRing_Another
// 0x0004 (0x0004 - 0x0000)
struct SL_FX_TravelRing_Another_C_ExecuteUbergraph_SL_FX_TravelRing_Another final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_SL_FX_TravelRing_Another_C_ExecuteUbergraph_SL_FX_TravelRing_Another;

}

