#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SL_FX_TravelRing_Another_LevelInstance_19

#include "Basic.hpp"

#include "SL_FX_TravelRing_Another_LevelInstance_19_classes.hpp"
#include "SL_FX_TravelRing_Another_LevelInstance_19_parameters.hpp"


namespace SDK
{

// Function SL_FX_TravelRing_Another_LevelInstance_19.SL_FX_TravelRing_Another_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void SL_FX_TravelRing_Another_LevelInstance_19::ASL_FX_TravelRing_Another_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_FX_TravelRing_Another_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SL_FX_TravelRing_Another_LevelInstance_19.SL_FX_TravelRing_Another_C.ExecuteUbergraph_SL_FX_TravelRing_Another
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void SL_FX_TravelRing_Another_LevelInstance_19::ASL_FX_TravelRing_Another_C::ExecuteUbergraph_SL_FX_TravelRing_Another(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SL_FX_TravelRing_Another_C", "ExecuteUbergraph_SL_FX_TravelRing_Another");

	Params::SL_FX_TravelRing_Another_C_ExecuteUbergraph_SL_FX_TravelRing_Another Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

