#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ResultRate

#include "Basic.hpp"

#include "WBP_ResultRate_classes.hpp"
#include "WBP_ResultRate_parameters.hpp"


namespace SDK
{

// Function WBP_ResultRate.WBP_ResultRate_C.BndEvt__WBP_ResultRate_Button_Screen_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_ResultRate_C::BndEvt__WBP_ResultRate_Button_Screen_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_C", "BndEvt__WBP_ResultRate_Button_Screen_K2Node_ComponentBoundEvent_0_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate.WBP_ResultRate_C.CloseTips
// (BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_C::CloseTips()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_C", "CloseTips");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate.WBP_ResultRate_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_ResultRate_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate.WBP_ResultRate_C.EndProc
// (BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_C::EndProc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_C", "EndProc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate.WBP_ResultRate_C.ExecuteUbergraph_WBP_ResultRate
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_C::ExecuteUbergraph_WBP_ResultRate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_C", "ExecuteUbergraph_WBP_ResultRate");

	Params::WBP_ResultRate_C_ExecuteUbergraph_WBP_ResultRate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate.WBP_ResultRate_C.SetOpenTipsWindow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InOpenWindow                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_C::SetOpenTipsWindow(bool InOpenWindow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_C", "SetOpenTipsWindow");

	Params::WBP_ResultRate_C_SetOpenTipsWindow Parms{};

	Parms.InOpenWindow = InOpenWindow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate.WBP_ResultRate_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_C", "Tick");

	Params::WBP_ResultRate_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

