#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ResultRate_Sub_RankBand

#include "Basic.hpp"

#include "WBP_ResultRate_Sub_RankBand_classes.hpp"
#include "WBP_ResultRate_Sub_RankBand_parameters.hpp"


namespace SDK
{

// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.ExecuteUbergraph_WBP_ResultRate_Sub_RankBand
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_Sub_RankBand_C::ExecuteUbergraph_WBP_ResultRate_Sub_RankBand(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "ExecuteUbergraph_WBP_ResultRate_Sub_RankBand");

	Params::WBP_ResultRate_Sub_RankBand_C_ExecuteUbergraph_WBP_ResultRate_Sub_RankBand Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_Sub_RankBand_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "PreConstruct");

	Params::WBP_ResultRate_Sub_RankBand_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.RateNotice
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Current                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_Sub_RankBand_C::RateNotice(double Current)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "RateNotice");

	Params::WBP_ResultRate_Sub_RankBand_C_RateNotice Parms{};

	Parms.Current = Current;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_Sub_RankBand_C::SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_Sub_RankBand_C::SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_1
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_Sub_RankBand_C::SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_2
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_Sub_RankBand_C::SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_3
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_Sub_RankBand_C::SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_4
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_ResultRate_Sub_RankBand_C::SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SequenceEvent__ENTRYPOINTWBP_ResultRate_Sub_RankBand_4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SetAnimateImpl
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ERateRank                               NowRank_in                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ERateRank                               NextRank_in                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_Sub_RankBand_C::SetAnimateImpl(ERateRank NowRank_in, ERateRank NextRank_in)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SetAnimateImpl");

	Params::WBP_ResultRate_Sub_RankBand_C_SetAnimateImpl Parms{};

	Parms.NowRank_in = NowRank_in;
	Parms.NextRank_in = NextRank_in;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SetNextRankImpl
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ERateRank                               NextRank_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_Sub_RankBand_C::SetNextRankImpl(ERateRank NextRank_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SetNextRankImpl");

	Params::WBP_ResultRate_Sub_RankBand_C_SetNextRankImpl Parms{};

	Parms.NextRank_0 = NextRank_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.SetNowRankImpl
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ERateRank                               NowRank_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_Sub_RankBand_C::SetNowRankImpl(ERateRank NowRank_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "SetNowRankImpl");

	Params::WBP_ResultRate_Sub_RankBand_C_SetNowRankImpl Parms{};

	Parms.NowRank_0 = NowRank_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ResultRate_Sub_RankBand.WBP_ResultRate_Sub_RankBand_C.StartRankAnim
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ERateRank                               End                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bRankUp                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ResultRate_Sub_RankBand_C::StartRankAnim(ERateRank End, bool bRankUp)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ResultRate_Sub_RankBand_C", "StartRankAnim");

	Params::WBP_ResultRate_Sub_RankBand_C_StartRankAnim Parms{};

	Parms.End = End;
	Parms.bRankUp = bRankUp;

	UObject::ProcessEvent(Func, &Parms);
}

}

