#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EndMenu_Sub_ChallengeInfo

#include "Basic.hpp"

#include "WBP_EndMenu_Sub_ChallengeInfo_classes.hpp"
#include "WBP_EndMenu_Sub_ChallengeInfo_parameters.hpp"


namespace SDK
{

// Function WBP_EndMenu_Sub_ChallengeInfo.WBP_EndMenu_Sub_ChallengeInfo_C.ShowOnly
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EChallengeId                            ChallengeId                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EndMenu_Sub_ChallengeInfo_C::ShowOnly(EChallengeId ChallengeId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndMenu_Sub_ChallengeInfo_C", "ShowOnly");

	Params::WBP_EndMenu_Sub_ChallengeInfo_C_ShowOnly Parms{};

	Parms.ChallengeId = ChallengeId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EndMenu_Sub_ChallengeInfo.WBP_EndMenu_Sub_ChallengeInfo_C.ShowChallengeInfo
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EChallengeId                            InChallengeId                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsShowOnly                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EndMenu_Sub_ChallengeInfo_C::ShowChallengeInfo(EChallengeId InChallengeId, bool bIsShowOnly)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndMenu_Sub_ChallengeInfo_C", "ShowChallengeInfo");

	Params::WBP_EndMenu_Sub_ChallengeInfo_C_ShowChallengeInfo Parms{};

	Parms.InChallengeId = InChallengeId;
	Parms.bIsShowOnly = bIsShowOnly;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EndMenu_Sub_ChallengeInfo.WBP_EndMenu_Sub_ChallengeInfo_C.OnEndChallengeInfoInAnim
// (BlueprintCallable, BlueprintEvent)

void UWBP_EndMenu_Sub_ChallengeInfo_C::OnEndChallengeInfoInAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndMenu_Sub_ChallengeInfo_C", "OnEndChallengeInfoInAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EndMenu_Sub_ChallengeInfo.WBP_EndMenu_Sub_ChallengeInfo_C.ExecuteUbergraph_WBP_EndMenu_Sub_ChallengeInfo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EndMenu_Sub_ChallengeInfo_C::ExecuteUbergraph_WBP_EndMenu_Sub_ChallengeInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EndMenu_Sub_ChallengeInfo_C", "ExecuteUbergraph_WBP_EndMenu_Sub_ChallengeInfo");

	Params::WBP_EndMenu_Sub_ChallengeInfo_C_ExecuteUbergraph_WBP_EndMenu_Sub_ChallengeInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

