#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EndMenu_UserReport_Sub_RankingTable

#include "Basic.hpp"

#include "UnionSystem_structs.hpp"
#include "Engine_structs.hpp"
#include "UNION_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EndMenu_UserReport_Sub_RankingTable.WBP_EndMenu_UserReport_Sub_RankingTable_C
// 0x0008 (0x06B8 - 0x06B0)
class UWBP_EndMenu_UserReport_Sub_RankingTable_C final : public URaceEndMenuUserReportPlayerButtonWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void OnLoaded_56904B9545857B027A39888EF535E5A7(class UObject* Loaded);
	void ExecuteUbergraph_WBP_EndMenu_UserReport_Sub_RankingTable(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_EndMenu_UserReport_Sub_RankingTable_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_EndMenu_UserReport_Sub_RankingTable_C")
	}
	static class UWBP_EndMenu_UserReport_Sub_RankingTable_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EndMenu_UserReport_Sub_RankingTable_C>();
	}
};
DUMPER7_ASSERTS_UWBP_EndMenu_UserReport_Sub_RankingTable_C;

}

