#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EndMenu_UserReport_Window

#include "Basic.hpp"

#include "UNION_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_EndMenu_UserReport_Window.WBP_EndMenu_UserReport_Window_C
// 0x0000 (0x0380 - 0x0380)
class UWBP_EndMenu_UserReport_Window_C final : public URaceEndMenuUserReportWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_EndMenu_UserReport_Window_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_EndMenu_UserReport_Window_C")
	}
	static class UWBP_EndMenu_UserReport_Window_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_EndMenu_UserReport_Window_C>();
	}
};
DUMPER7_ASSERTS_UWBP_EndMenu_UserReport_Window_C;

}

