#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Hint_Sub_11001

#include "Basic.hpp"

#include "WBP_Hint_Sub_11001_classes.hpp"
#include "WBP_Hint_Sub_11001_parameters.hpp"


namespace SDK
{

// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_3
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hint_Sub_11001_C::SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hint_Sub_11001_C", "SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_2
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hint_Sub_11001_C::SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hint_Sub_11001_C", "SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_1
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hint_Sub_11001_C::SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hint_Sub_11001_C", "SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hint_Sub_11001_C::SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hint_Sub_11001_C", "SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_0");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_Hint_Sub_11001_C::SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hint_Sub_11001_C", "SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.SequenceEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InIndex                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hint_Sub_11001_C::SequenceEvent(int32 InIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hint_Sub_11001_C", "SequenceEvent");

	Params::WBP_Hint_Sub_11001_C_SequenceEvent Parms{};

	Parms.InIndex = InIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.ExecuteUbergraph_WBP_Hint_Sub_11001
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Hint_Sub_11001_C::ExecuteUbergraph_WBP_Hint_Sub_11001(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Hint_Sub_11001_C", "ExecuteUbergraph_WBP_Hint_Sub_11001");

	Params::WBP_Hint_Sub_11001_C_ExecuteUbergraph_WBP_Hint_Sub_11001 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

