#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FestaResult_PointReward

#include "Basic.hpp"

#include "WBP_FestaResult_PointReward_classes.hpp"
#include "WBP_FestaResult_PointReward_parameters.hpp"


namespace SDK
{

// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.BndEvt__WBP_FestaResult_PointReward_Button_front_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_FestaResult_PointReward_C::BndEvt__WBP_FestaResult_PointReward_Button_front_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "BndEvt__WBP_FestaResult_PointReward_Button_front_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.BndEvt__WBP_FestaResult_PointReward_Button_front_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_FestaResult_PointReward_C::BndEvt__WBP_FestaResult_PointReward_Button_front_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "BndEvt__WBP_FestaResult_PointReward_Button_front_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.ContributionInfo
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::ContributionInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "ContributionInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.ContributionMain
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::ContributionMain()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "ContributionMain");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.CreateMachine
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FUserMachineCustomizeData& CustomizeData                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// EMachineId                              MachineId                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PositionIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   RacerIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::CreateMachine(const struct FUserMachineCustomizeData& CustomizeData, EMachineId MachineId, int32 PositionIndex, int32 RacerIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "CreateMachine");

	Params::WBP_FestaResult_PointReward_C_CreateMachine Parms{};

	Parms.CustomizeData = std::move(CustomizeData);
	Parms.MachineId = MachineId;
	Parms.PositionIndex = PositionIndex;
	Parms.RacerIndex = RacerIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.CreateRacerModel
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   RacerIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   PositionIndex                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::CreateRacerModel(int32 RacerIndex, int32 PositionIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "CreateRacerModel");

	Params::WBP_FestaResult_PointReward_C_CreateRacerModel Parms{};

	Parms.RacerIndex = RacerIndex;
	Parms.PositionIndex = PositionIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.ExecuteUbergraph_WBP_FestaResult_PointReward
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::ExecuteUbergraph_WBP_FestaResult_PointReward(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "ExecuteUbergraph_WBP_FestaResult_PointReward");

	Params::WBP_FestaResult_PointReward_C_ExecuteUbergraph_WBP_FestaResult_PointReward Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.FestaPointReward
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::FestaPointReward()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "FestaPointReward");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.GetFestaDriverId_impl
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   RacerIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EDriverId*                              DriverId                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::GetFestaDriverId_impl(int32 RacerIndex, EDriverId* DriverId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "GetFestaDriverId_impl");

	Params::WBP_FestaResult_PointReward_C_GetFestaDriverId_impl Parms{};

	Parms.RacerIndex = RacerIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (DriverId != nullptr)
		*DriverId = Parms.DriverId;
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.GetResultPlayingStageId
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EStageId*                               OutStageId                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FTransform*                      OutTransform                                           (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::GetResultPlayingStageId(EStageId* OutStageId, struct FTransform* OutTransform)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "GetResultPlayingStageId");

	Params::WBP_FestaResult_PointReward_C_GetResultPlayingStageId Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutStageId != nullptr)
		*OutStageId = Parms.OutStageId;

	if (OutTransform != nullptr)
		*OutTransform = std::move(Parms.OutTransform);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.Is List Exist Driver Id
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EDriverId                               DriverId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   bIsExist_0                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::Is_List_Exist_Driver_Id(int32 Index_0, EDriverId DriverId, bool* bIsExist_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "Is List Exist Driver Id");

	Params::WBP_FestaResult_PointReward_C_Is_List_Exist_Driver_Id Parms{};

	Parms.Index_0 = Index_0;
	Parms.DriverId = DriverId;

	UObject::ProcessEvent(Func, &Parms);

	if (bIsExist_0 != nullptr)
		*bIsExist_0 = Parms.bIsExist_0;
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.Is Load Ok
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   bIsLoadOk                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::Is_Load_Ok(bool* bIsLoadOk)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "Is Load Ok");

	Params::WBP_FestaResult_PointReward_C_Is_Load_Ok Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bIsLoadOk != nullptr)
		*bIsLoadOk = Parms.bIsLoadOk;
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.LoadModelAll
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::LoadModelAll()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "LoadModelAll");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.OnFinishedFade
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EUnionUIFadeDirection                   FadeDirection                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::OnFinishedFade(EUnionUIFadeDirection FadeDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "OnFinishedFade");

	Params::WBP_FestaResult_PointReward_C_OnFinishedFade Parms{};

	Parms.FadeDirection = FadeDirection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.OnResultRewardDisplayEnd_Event
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::OnResultRewardDisplayEnd_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "OnResultRewardDisplayEnd_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.OnStreakRewardEnd_Event
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::OnStreakRewardEnd_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "OnStreakRewardEnd_Event");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.Open
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.OpenTeamRankText
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::OpenTeamRankText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "OpenTeamRankText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "PreConstruct");

	Params::WBP_FestaResult_PointReward_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.RewardProcess
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::RewardProcess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "RewardProcess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetCompleteBonusWindow
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::SetCompleteBonusWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetCompleteBonusWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetDonpaTicketGetWindow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   TicketAdd                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::SetDonpaTicketGetWindow(int32 TicketAdd)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetDonpaTicketGetWindow");

	Params::WBP_FestaResult_PointReward_C_SetDonpaTicketGetWindow Parms{};

	Parms.TicketAdd = TicketAdd;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetItemWindowPos
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  posX                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::SetItemWindowPos(double posX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetItemWindowPos");

	Params::WBP_FestaResult_PointReward_C_SetItemWindowPos Parms{};

	Parms.posX = posX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetPartyColorIndex
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   ColorIndex                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::SetPartyColorIndex(int32 ColorIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetPartyColorIndex");

	Params::WBP_FestaResult_PointReward_C_SetPartyColorIndex Parms{};

	Parms.ColorIndex = ColorIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetRankUpRewardGetWindow
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::SetRankUpRewardGetWindow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetRankUpRewardGetWindow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetStreakRewardGetWindow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// ERewardType                             Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ItemId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::SetStreakRewardGetWindow(ERewardType Type, int32 ItemId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetStreakRewardGetWindow");

	Params::WBP_FestaResult_PointReward_C_SetStreakRewardGetWindow Parms{};

	Parms.Type = Type;
	Parms.ItemId = ItemId;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetupBG
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::SetupBG()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetupBG");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.SetupResultBG
// (BlueprintCallable, BlueprintEvent)

void UWBP_FestaResult_PointReward_C::SetupResultBG()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "SetupResultBG");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_FestaResult_PointReward.WBP_FestaResult_PointReward_C.UpdateItemWindow
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsGetReward                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_FestaResult_PointReward_C::UpdateItemWindow(bool bIsGetReward)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_FestaResult_PointReward_C", "UpdateItemWindow");

	Params::WBP_FestaResult_PointReward_C_UpdateItemWindow Parms{};

	Parms.bIsGetReward = bIsGetReward;

	UObject::ProcessEvent(Func, &Parms);
}

}

