#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FooterMenu_Sub_CommonBtn

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UNION_classes.hpp"
#include "UnionUI_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_FooterMenu_Sub_CommonBtn.WBP_FooterMenu_Sub_CommonBtn_C
// 0x0028 (0x0360 - 0x0338)
class UWBP_FooterMenu_Sub_CommonBtn_C final : public UCommonMenuFooterButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Btn_Active;                                        // 0x0340(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Btn_Push;                                          // 0x0348(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UUnionRichTextBlock*                    TXT_BtnName;                                       // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         Index_0;                                           // 0x0358(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EUIButtonIconType                             ButtonIconType;                                    // 0x035C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_WBP_FooterMenu_Sub_CommonBtn(int32 EntryPoint);
	void OnAcceptKeyPressed();
	void OnBackKeyPressed();
	void OnFaceButtonLeftPressed();
	void OnFaceButtonTopPressed();
	void OnLeftShoulderPressed();
	void OnRightShoulderPressed();
	void OnVisibilityChanged_イベント(ESlateVisibility InVisibility);
	void PreConstruct(bool IsDesignTime);
	void SetIconGauge(float InGaugeParam);
	void SetIconType(int32 InButtonIconIndex, EUIButtonIconType InButtonIconType);
	void SetText(const class FText& InText);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_FooterMenu_Sub_CommonBtn_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_FooterMenu_Sub_CommonBtn_C")
	}
	static class UWBP_FooterMenu_Sub_CommonBtn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FooterMenu_Sub_CommonBtn_C>();
	}
};
DUMPER7_ASSERTS_UWBP_FooterMenu_Sub_CommonBtn_C;

}

