#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Friend_Popup_WindowAnimation

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UNION_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Friend_Popup_WindowAnimation.WBP_Friend_Popup_WindowAnimation_C
// 0x0040 (0x0330 - 0x02F0)
class UWBP_Friend_Popup_WindowAnimation_C final : public UFriendListConfirmAnimationWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       LobbyInvitation_Send_Out;                          // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LobbyInvitation_Default_Out;                       // 0x0300(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LobbyInvitation_Default_Loop;                      // 0x0308(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LobbyInvitation_Send_In;                           // 0x0310(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       LobbyInvitation_Reception_In;                      // 0x0318(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Light_01;                                          // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 LobbyInvitation;                                   // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void PlayAnimationOut(bool bInSend);
	void PlayAnimationIn(bool bInReception);
	void OnInitialized();
	void OnAnimationOutFinished_Internal();
	void OnAnimationInFinished();
	void ExecuteUbergraph_WBP_Friend_Popup_WindowAnimation(int32 EntryPoint);
	void BindAnimationEvent();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Friend_Popup_WindowAnimation_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Friend_Popup_WindowAnimation_C")
	}
	static class UWBP_Friend_Popup_WindowAnimation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Friend_Popup_WindowAnimation_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Friend_Popup_WindowAnimation_C;

}

