#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Hint_Sub_11001

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.SequenceEvent
// 0x0004 (0x0004 - 0x0000)
struct WBP_Hint_Sub_11001_C_SequenceEvent final
{
public:
	int32                                         InIndex;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Hint_Sub_11001_C_SequenceEvent;

// Function WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C.ExecuteUbergraph_WBP_Hint_Sub_11001
// 0x0008 (0x0008 - 0x0000)
struct WBP_Hint_Sub_11001_C_ExecuteUbergraph_WBP_Hint_Sub_11001 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_InIndex;                        // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_Hint_Sub_11001_C_ExecuteUbergraph_WBP_Hint_Sub_11001;

}

