#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Hint_Sub_11001

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UNION_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Hint_Sub_11001.WBP_Hint_Sub_11001_C
// 0x0020 (0x0308 - 0x02E8)
class UWBP_Hint_Sub_11001_C final : public UHint_Sub
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       B_Out;                                             // 0x02F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       A_Out;                                             // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       In;                                                // 0x0300(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_3();
	void SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_2();
	void SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_1();
	void SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001_0();
	void SequenceEvent__ENTRYPOINTWBP_Hint_Sub_11001();
	void SequenceEvent(int32 InIndex);
	void ExecuteUbergraph_WBP_Hint_Sub_11001(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Hint_Sub_11001_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Hint_Sub_11001_C")
	}
	static class UWBP_Hint_Sub_11001_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Hint_Sub_11001_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Hint_Sub_11001_C;

}

